services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.

    App\Tests\Resource\Fixture\:
        resource: "%kernel.project_dir%/tests/Resource/Fixture/*"
        tags:
            - { "name" : "doctrine.fixture.orm" }

    App\Shared\Infrastructure\Bus\CommandBus:
        public: true

    App\Shared\Infrastructure\Bus\QueryBus:
        public: true